#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="github.com/llvm"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/llvm"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/llvm"

REPOSITORY_LLVM_PROJECT_NAME="llvm-project"
REPOSITORY_LLVM_TEST_SUITE_NAME="llvm-test-suite"
REPOSITORY_LLVM_LNT_NAME="llvm-lnt"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_LLVM_PROJECT_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_LLVM_PROJECT_NAME}" \
        --branch "main"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_LLVM_TEST_SUITE_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_LLVM_TEST_SUITE_NAME}" \
        --branch "main"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_LLVM_LNT_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_LLVM_LNT_NAME}" \
        --branch "main"

    ProcessCommonPost
}

Process $@
