#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="gitlab.com/wpietersexyz"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/gitlab.com/wpietersexyz"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/gitlab.com/wpietersexyz"

REPOSITORY_SCRAPBOOK_NAME="scrapbook"
REPOSITORY_GAME_ASSETS_NAME="game-assets"
REPOSITORY_UNREALENGINE_1_1996_NAME="unrealengine-1-1996"
REPOSITORY_UNREALENGINE_1_1997_NAME="unrealengine-1-1997"
REPOSITORY_OPEN_NT_400_NAME="open-nt-400"
REPOSITORY_WINDOWS_10_NAME="windows-10"
REPOSITORY_WINDOWS_NT_350_NAME="windows-nt-350"
REPOSITORY_WINDOWS_NT_400_NAME="windows-nt-400"
REPOSITORY_WINDOWS_NT_600_NAME="windows-nt-600"
REPOSITORY_WINDOWS_RESEARCH_KERNEL_NAME="windows-research-kernel"
REPOSITORY_XBOX_NAME="xbox"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_SCRAPBOOK_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_SCRAPBOOK_NAME}" \
        --branch "main"

    if [[ ${PARAMETER_DISABLE_BUILD} -eq 0 ]];
    then
        cp \
            -f \
            "${THIS_SCRIPT_DIRECTORY}/user.bazelrc.scrapbook" \
            "${REPOSITORY_LOCAL_BASE_PATH}/${REPOSITORY_SCRAPBOOK_NAME}/user.bazelrc"
    fi

    ProcessBazel \
        --source-path "${REPOSITORY_LOCAL_BASE_PATH}/${REPOSITORY_SCRAPBOOK_NAME}" \
        --build-path "${BUILD_BASE_PATH}/${REPOSITORY_SCRAPBOOK_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_GAME_ASSETS_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_UNREALENGINE_1_1996_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_UNREALENGINE_1_1997_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_OPEN_NT_400_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_WINDOWS_10_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_WINDOWS_NT_350_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_WINDOWS_NT_400_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_WINDOWS_NT_600_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_WINDOWS_RESEARCH_KERNEL_NAME}" \
        --branch "main"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_XBOX_NAME}" \
        --branch "main"

    ProcessCommonPost
}

Process $@
