#!/bin/bash

source "/shared/randoms/synchronizer/shared"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}"

CONTENT_PROCESS_FILE="${LOCAL_ROOT_PATH}/targets/content/process"
DEVELOPMENT_PROCESS_FILE="${LOCAL_ROOT_PATH}/targets/development/process"
RANDOMS_PROCESS_FILE="${LOCAL_ROOT_PATH}/targets/randoms/process"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-process-content)
                declare DISABLE_PROCESS_CONTENT=1
                ;;
            --disable-process-development)
                declare DISABLE_PROCESS_DEVELOPMENT=1
                ;;
            --disable-process-randoms)
                declare DISABLE_PROCESS_RANDOMS=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    if [ -z "${DISABLE_PROCESS_CONTENT}" ];
    then
        "${CONTENT_PROCESS_FILE}" \
            --disable-clear
    fi

    if [ -z "${DISABLE_PROCESS_DEVELOPMENT}" ];
    then
        "${DEVELOPMENT_PROCESS_FILE}" \
            --disable-clear
    fi

    if [ -z "${DISABLE_PROCESS_RANDOMS}" ];
    then
        "${RANDOMS_PROCESS_FILE}" \
            --disable-clear
    fi
}

Process $@
