#!/bin/bash

source "/shared/randoms/synchronizer/shared"

SCRIPT_PATH="${SYNCHRONIZER_REPOSITORY_PATH}"

CONTENT_PROCESS_FILE="${SCRIPT_PATH}/targets/content/process"
DEVELOPMENT_PROCESS_FILE="${SCRIPT_PATH}/targets/development/process"
PERSONAL_PROCESS_FILE="${SCRIPT_PATH}/targets/personal/process"
RANDOMS_PROCESS_FILE="${SCRIPT_PATH}/targets/randoms/process"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-target-content)
                declare DISABLE_TARGET_CONTENT=1
                ;;
            --disable-target-development)
                declare DISABLE_TARGET_DEVELOPMENT=1
                ;;
            --disable-target-personal)
                declare DISABLE_TARGET_PERSONAL=1
                ;;
            --disable-target-randoms)
                declare DISABLE_TARGET_RANDOMS=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    if [ -z "${DISABLE_TARGET_CONTENT}" ];
    then
        "${CONTENT_PROCESS_FILE}" \
            --disable-clear
    fi

    if [ -z "${DISABLE_TARGET_DEVELOPMENT}" ];
    then
        "${DEVELOPMENT_PROCESS_FILE}" \
            --disable-clear
    fi

    if [ -z "${DISABLE_TARGET_PERSONAL}" ];
    then
        "${PERSONAL_PROCESS_FILE}" \
            --disable-clear
    fi

    if [ -z "${DISABLE_TARGET_RANDOMS}" ];
    then
        "${RANDOMS_PROCESS_FILE}" \
            --disable-clear
    fi
}

Process $@
