#!/bin/bash

source "/shared/randoms/synchronizer/shared"

SCRIPT_PATH="${SYNCHRONIZER_REPOSITORY_PATH}/targets/development"

SHARED_TOOLCHAIN_DOCKER_PATH="${SCRIPT_PATH}/toolchain/Dockerfile"
SHARED_TOOLCHAIN_DOCKER_TAG="development-toolchain"
SHARED_TOOLCHAIN_DOCKER_ROOT="${SCRIPT_PATH}/toolchain"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-toolchain)
                declare DISABLE_TOOLCHAIN=1
                ;;
            --disable-repositories)
                declare DISABLE_REPOSITORIES=1
                ;;
            --disable-repositories-clone)
                declare DISABLE_REPOSITORIES_CLONE=1
                ;;
            --disable-repositories-build)
                declare DISABLE_REPOSITORIES_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    if [ -z "${DISABLE_TOOLCHAIN}" ];
    then
        echo "************************************************************************************************************************"
        echo "* DEVELOPMENT TOOLCHAIN                                                                                                *"
        echo "************************************************************************************************************************"
        echo ""

        echo "=== BUILD CONTAINER IMAGE =============================================================================================="
        echo ""

        docker                                          \
            build                                       \
                --file ${SHARED_TOOLCHAIN_DOCKER_PATH}  \
                --tag ${SHARED_TOOLCHAIN_DOCKER_TAG}    \
                ${SHARED_TOOLCHAIN_DOCKER_ROOT}

        echo ""
    fi

    if [ -z "${DISABLE_REPOSITORIES}" ];
    then
        local REPOSITORIES_ARGUMENTS=()

        REPOSITORIES_ARGUMENTS+=("--disable-clear")

        if [ ! -z "${DISABLE_REPOSITORIES_CLONE}" ];
        then
            REPOSITORIES_ARGUMENTS+=("--disable-clone")
        fi

        if [ ! -z "${DISABLE_REPOSITORIES_BUILD}" ];
        then
            REPOSITORIES_ARGUMENTS+=("--disable-build")
        fi

        "${SCRIPT_PATH}/repositories/process" ${REPOSITORIES_ARGUMENTS[@]}
    fi
}

Process $@
