#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "Docker : development-git"

    docker \
        build \
            --tag development-git \
            --build-arg USER_ID=$(id -u) \
            --build-arg GROUP_ID=$(id -g) \
            --file "${THIS_SCRIPT_DIRECTORY}/process_docker_git.Dockerfile" \
            ${THIS_SCRIPT_DIRECTORY}

    ProcessCommonPost
}

Process $@
