#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/android.googlesource.com"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/android.googlesource.com"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "android.googlesource.com"

    mkdir -p "${REPOSITORY_LOCAL_BASE_PATH}"
    
    pushd "${REPOSITORY_LOCAL_BASE_PATH}" > /dev/null

    /home/wpieterse/bin/repo init -u https://android.googlesource.com/platform/manifest -b master

    /home/wpieterse/bin/repo sync -j 8

    popd > /dev/null

    ProcessCommonPost
}

Process $@
