#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "toolchains/base"

    docker \
        build \
            --tag "toolchains/base" \
            --file "${THIS_SCRIPT_DIRECTORY}/Dockerfile" \
            "${THIS_SCRIPT_DIRECTORY}/../.empty"

    ProcessCommonPost
}

Process $@
