---
version: "2.1"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Africa/Johannesburg"
      - DELUGE_LOGLEVEL=error
    volumes:
      - /shared/content/.private/deluge/config:/config
      - /shared/content/downloads/index:/downloads/index
      - /shared/content/downloads/active:/downloads/active
      - /shared/content/downloads/done:/downloads/done
