#!/bin/bash

source "/shared/randoms/synchronizer/variables"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/content"

DELUGE_COMPOSE_FILE="${LOCAL_ROOT_PATH}/deluge.yaml"
PLEX_COMPOSE_FILE="${LOCAL_ROOT_PATH}/plex.yaml"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-prune)
                declare DISABLE_PRUNE=1
                ;;
            --disable-service-deluge)
                declare DISABLE_SERVICE_DELUGE=1
                ;;
            --disable-service-plex)
                declare DISABLE_SERVICE_PLEX=1
                ;;
            *)
                LogError "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    if [ -z "${DISABLE_SERVICE_DELUGE}" ];
    then
        echo "************************************************************************************************************************"
        echo "* DELUGE SERVER CONTAINER                                                                                              *"
        echo "************************************************************************************************************************"
        echo ""

        echo "=== RECREATE CONTAINER ================================================================================================="
        echo ""

        docker-compose                      \
            --project-name "deluge-project" \
            --file "${DELUGE_COMPOSE_FILE}" \
            up                              \
                --detach                    \
                --force-recreate            \
                --build                     \
                --remove-orphans

        echo ""
    fi

    if [ -z "${DISABLE_SERVICE_PLEX}" ];
    then
        echo "************************************************************************************************************************"
        echo "* PLEX SERVER CONTAINER                                                                                                *"
        echo "************************************************************************************************************************"
        echo ""

        echo "=== RECREATE CONTAINER ================================================================================================="
        echo ""

        docker-compose                      \
            --project-name "plex-project"   \
            --file "${PLEX_COMPOSE_FILE}"   \
            up                              \
                --detach                    \
                --force-recreate            \
                --build                     \
                --remove-orphans

        echo ""
    fi

    if [ -z "${DISABLE_PRUNE}" ];
    then
        echo "=== PRUNNING UNUSED CONTAINERS ========================================================================================="
        echo ""

        docker image prune --force

        echo ""
    fi
}

Process $@
