#!/bin/bash

source "/shared/randoms/synchronizer/shared"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/development/repositories/github.com/axboe"

REMOTE_DEVELOPMENT_PATH="github.com/axboe"
LOCAL_DEVELOPMENT_PATH="${DEVELOPMENT_ROOT_PATH}/github.com/axboe"
LOCAL_BUILD_PATH="${BUILDS_OTHER_ROOT_PATH}/server-pc/github.com/axboe"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-clone)
                declare DISABLE_CLONE=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/axboe/liburing                                                                                            *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "liburing"                               \
            --branch "master"
    fi

    echo ""
}

Process $@
