#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CallSubScripts                                              \
        --root "${THIS_SCRIPT_DIRECTORY}"                       \
        --script "clone_pub_scm_linux_kernel_git_torvalds"

    ProcessPost
}

Process $@
