#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessGitRepositories \
        --remote-base-path "git://git.kernel.org/pub/scm/linux/kernel/git/torvalds" \
        --local-base-path "${SERVER_PC_DEVELOPMENT_PATH}/git.kernel.org/pub/scm/linux/kernel/git/torvalds" \
        --repository "linux" --branch "master"

    ProcessCommonPost
}

Process $@
