#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories \
        --remote_base_path "git://git.kernel.org/pub/scm/linux/kernel/git/torvalds" \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/git.kernel.org/pub/scm/linux/kernel/git/torvalds" \
        --repository "linux" --branch "master"

    ProcessPost
}

Process $@
