#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessSubScripts \
        --root "${THIS_SCRIPT_DIRECTORY}" \
        --script "process_pub_scm_linux_kernel_git_torvalds"

    ProcessCommonPost
}

Process $@
