#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="github-wpieterse2825:EpicGames"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/EpicGames"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/EpicGames"

REPOSITORY_UNREALENGINE_NAME="UnrealEngine"
REPOSITORY_UNREALTOURNAMENT_NAME="UnrealTournament"
REPOSITORY_BLENDERTOOLS_NAME="BlenderTools"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_UNREALENGINE_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_UNREALENGINE_NAME}" \
        --branch "release"

    # pushd ${REPOSITORY_LOCAL_BASE_PATH}/${REPOSITORY_UNREALENGINE_NAME} > /dev/null
    # ./Setup.sh
    # popd > /dev/null

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_UNREALTOURNAMENT_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_UNREALTOURNAMENT_NAME}" \
        --branch "clean-master"

    # pushd ${REPOSITORY_LOCAL_BASE_PATH}/${REPOSITORY_UNREALTOURNAMENT_NAME} > /dev/null
    # ./Setup.sh
    # popd > /dev/null

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_BLENDERTOOLS_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_BLENDERTOOLS_NAME}" \
        --branch "master"

    ProcessCommonPost
}

Process $@
