#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/haiku"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/haiku"  \
        --repository "haiku" --branch "master"                              \
        --repository "firmware" --branch "master"                           \
        --repository "haikudepotserver" --branch "master"                   \
        --repository "infrastructure" --branch "master"                     \
        --repository "website" --branch "master"                            \
        --repository "buildtools" --branch "master"                         \
        --repository "artwork" --branch "master"

    ProcessPost
}

Process $@
