#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/apple"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/apple"  \
        --repository "darwin-xnu" --branch "main"                           \
        --repository "swift" --branch "main"                                \
        --repository "swift-llbuild" --branch "main"                        \
        --repository "foundationdb" --branch "main"                         \
        --repository "indexstore-db" --branch "main"

    ProcessPost
}

Process $@
