#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/facebook"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/facebook"   \
        --repository "rocksdb" --branch "main"                                  \
        --repository "proxygen" --branch "master"                               \
        --repository "folly" --branch "master"                                  \
        --repository "fbthrift" --branch "master"                               \
        --repository "hermes" --branch "master"

    ProcessPost
}

Process $@
