#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/svkaiser"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/svkaiser"   \
        --repository "PowerslaveEX" --branch "master"                           \
        --repository "ForsakenEXTools" --branch "master"                        \
        --repository "dlight" --branch "master"                                 \
        --repository "dlightgui" --branch "master"                              \
        --repository "KexLIB" --branch "master"                                 \
        --repository "TurokEX" --branch "master"                                \
        --repository "doom64DS" --branch "master"

    #    --repository "Doom64EX" --branch "master"                               \

    ProcessPost
}

Process $@
