#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/mysql"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/mysql"  \
        --repository "mysql-server" --branch "main"                         \
        --repository "mysql-shell-plugins" --branch "master"                \
        --repository "mysql-operator" --branch "master"                     \
        --repository "mysql-connector-cpp" --branch "master"                \
        --repository "mysql-workbench" --branch "master"                    \
        --repository "mysql-docker" --branch "master"                       \
        --repository "mysql-shell" --branch "master"                        \
        --repository "mysql-sys" --branch "master"                          \
        --repository "mysql-proxy" --branch "master"

    ProcessPost
}

Process $@
