#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/graninas"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/graninas"   \
        --repository "cpp_functional_programming" --branch "master"

    ProcessPost
}

Process $@
