#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                                    \
        --remote_base_path "https://github.com/facebookexperimental"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/facebookexperimental"   \
        --repository "libunifex" --branch "main"                                            \
        --repository "skybison" --branch "trunk"

    ProcessPost
}

Process $@
