#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://github.com/TrenchBroom"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/TrenchBroom"    \
        --repository "TrenchBroom" --branch "master"                                \
        --repository "vecmath" --branch "master"                                    \
        --repository "TrenchBroom.github.io" --branch "master"                      \
        --repository "manual" --branch "gh-pages"

    ProcessPost
}

Process $@
