#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/ISSOtm"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/ISSOtm" \
        --repository "gb-starter-kit" --branch "master"                     \
        --repository "gb-boilerplate" --branch "master"                     \
        --repository "slides" --branch "master"                             \
        --repository "issotm.github.io" --branch "master"                   \
        --repository "gb-asm-tutorial" --branch "master"                    \
        --repository "gb-bootroms" --branch "master"                        \
        --repository "sgb-bios" --branch "master"                           \
        --repository "motherboard-gb" --branch "master"                     \
        --repository "fortISSimO" --branch "master"

    ProcessPost
}

Process $@
