#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/llvm"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/llvm"   \
        --repository "llvm-project" --branch "main"                         \
        --repository "circt" --branch "master"                              \
        --repository "mlir-www" --branch "master"                           \
        --repository "circt-www" --branch "master"                          \
        --repository "torch-mlir" --branch "master"                         \
        --repository "llvm-zorg" --branch "master"                          \
        --repository "llvm-www" --branch "master"                           \
        --repository "llvm-test-suite" --branch "master"                    \
        --repository "llvm-iwg" --branch "master"                           \
        --repository "llvm-foundation-www" --branch "master"                \
        --repository "llvm-lnt" --branch "master"                           \
        --repository "actions" --branch "master"                            \
        --repository "www-releases" --branch "master"                       \
        --repository "clangd-www" --branch "master"

    ProcessPost
}

Process $@
