#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://github.com/KhronosGroup"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/KhronosGroup"   \
        --repository "glslang" --branch "master"                                    \
        --repository "Vulkan-ExtensionLayer" --branch "master"                      \
        --repository "SPIRV-LLVM-Translator" --branch "master"                      \
        --repository "Vulkan-ValidationLayers" --branch "master"                    \
        --repository "SYCL_Reference" --branch "main"                               \
        --repository "glTF-Blender-IO" --branch "master"                            \
        --repository "Vulkan-Docs" --branch "master"                                \
        --repository "VK-GL-CTS" --branch "master"                                  \
        --repository "OpenXR-SDK-Source" --branch "main"                            \
        --repository "Vulkan-Samples" --branch "master"                             \
        --repository "glTF-Validator" --branch "main"                               \
        --repository "OpenCL-CTS" --branch "main"                                   \
        --repository "glTF-Sample-Models" --branch "master"                         \
        --repository "Vulkan-Profiles" --branch "master"                            \
        --repository "Vulkan-Loader" --branch "master"                              \
        --repository "Vulkan-Tools" --branch "master"                               \
        --repository "Vulkan-Headers" --branch "master"                             \
        --repository "SPIRV-Tools" --branch "master"                                \
        --repository "OpenCL-SDK" --branch "main"                                   \
        --repository "glTF" --branch "main"                                         \
        --repository "SYCL-CTS" --branch "SYCL-2020"                                \
        --repository "SYCL-Docs" --branch "SYCL-2020/master"                        \
        --repository "OpenCL-ICD-Loader" --branch "main"                            \
        --repository "Vulkan-Hpp" --branch "master"                                 \
        --repository "OpenCL-Guide" --branch "main"                                 \
        --repository "OpenCL-Registry" --branch "main"                              \
        --repository "libclcxx" --branch "main"                                     \
        --repository "Vulkan-Guide" --branch "master"                               \
        --repository "VK-GL-CTS-Tools" --branch "main"                              \
        --repository "KTX-Software" --branch "master"                               \
        --repository "SPIRV-Cross" --branch "master"                                \
        --repository "OpenXR-CTS" --branch "devel"                                  \
        --repository "OpenCL-Docs" --branch "main"                                  \
        --repository "KTX-Registry" --branch "main"                                 \
        --repository "SPIRV-Guide" --branch "master"                                \
        --repository "SPIRV-Headers" --branch "master"                              \
        --repository "SPIRV-Registry" --branch "main"                               \
        --repository "OpenCL-Headers" --branch "main"                               \
        --repository "OpenCL-CLHPP" --branch "main"                                 \
        --repository "glTF-Tutorials" --branch "master"                             \
        --repository "OpenCL-Layers" --branch "main"                                \
        --repository "Vulkan-Samples-Assets" --branch "master"                      \
        --repository "SYCL-Registry" --branch "main"

    ProcessPost
}

Process $@
