#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/bazelbuild"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/bazelbuild" \
        --repository "bazel" --branch "master"                                  \
        --repository "rules_go" --branch "master"                               \
        --repository "rules_apple" --branch "master"                            \
        --repository "rules_pkg" --branch "main"                                \
        --repository "bazel-skylib" --branch "main"                             \
        --repository "rules_kotlin" --branch "master"                           \
        --repository "rules_rust" --branch "main"                               \
        --repository "platforms" --branch "main"                                \
        --repository "rules_python" --branch "main"                             \
        --repository "bazelisk" --branch "master"                               \
        --repository "rules_cc" --branch "main"                                 \
        --repository "rules_proto" --branch "master"                            \
        --repository "continuous-integration" --branch "master"                 \
        --repository "examples" --branch "main"                                 \
        --repository "rules_docker" --branch "master"                           \
        --repository "rules_swift" --branch "master"                            \
        --repository "bazel-central-registry" --branch "main"                   \
        --repository "bazel-integration-testing" --branch "master"

    ProcessPost
}

Process $@
