#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/OpenTTD"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/OpenTTD"    \
        --repository "OpenTTD" --branch "master"                                \
        --repository "wiki-data" --branch "main"                                \
        --repository "BaNaNaS" --branch "main"                                  \
        --repository "website" --branch "main"                                  \
        --repository "master-server-web" --branch "main"                        \
        --repository "master-server" --branch "main"                            \
        --repository "game-coordinator" --branch "main"                         \
        --repository "eints" --branch "main"                                    \
        --repository "bananas-server" --branch "main"                           \
        --repository "bananas-frontend-web" --branch "main"                     \
        --repository "bananas-frontend-cli" --branch "main"                     \
        --repository "bananas-api" --branch "main"                              \
        --repository "appstore-data" --branch "main"                            \
        --repository "nml" --branch "main"                                      \
        --repository "OpenMSX" --branch "main"                                  \
        --repository "OpenSFX" --branch "main"                                  \
        --repository "OpenGFX" --branch "main"                                  \
        --repository "actions" --branch "main"                                  \
        --repository "py-protocol" --branch "main"                              \
        --repository "workflows" --branch "main"                                \
        --repository "aws-infra" --branch "main"                                \
        --repository "py-helpers" --branch "main"                               \
        --repository "team" --branch "main"                                     \
        --repository "OpenTTD-git-hooks" --branch "main"                        \
        --repository "catcodec" --branch "main"                                 \
        --repository "eints-sandbox" --branch "main"                            \
        --repository "osie" --branch "main"                                     \
        --repository "grfcodec" --branch "main"                                 \
        --repository "CompileFarm" --branch "main"                              \
        --repository "binaries-redirect" --branch "main"                        \
        --repository "binaries-proxy" --branch "main"                           \
        --repository "infrastructure" --branch "main"                           \
        --repository "musa" --branch "main"                                     \
        --repository "MasterServer" --branch "main"

    ProcessPost
}

Process $@
