#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://github.com/bbbradsmith"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/bbbradsmith"    \
        --repository "NESertGolfing" --branch "master"                              \
        --repository "nsfplay" --branch "master"                                    \
        --repository "huffmunch" --branch "master"                                  \
        --repository "nes-audio-tests" --branch "master"

    ProcessPost
}

Process $@
