#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/storm-devs"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/storm-devs" \
        --repository "storm-engine" --branch "develop"                          \
        --repository "sd-teho-public" --branch "develop-eng"                    \
        --repository "coas" --branch "master"                                   \
        --repository "potc" --branch "master"                                   \
        --repository "seadogs-file-formats" --branch "master"

    ProcessPost
}

Process $@
