#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/aerospike"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/aerospike"  \
        --repository "aql" --branch "main"                                      \
        --repository "aerospike-client-c" --branch "master"                     \
        --repository "aerospike-tools-backup" --branch "master"                 \
        --repository "aerospike-admin" --branch "master"                        \
        --repository "aerospike-client-python" --branch "master"                \
        --repository "kubernetes-operator" --branch "main"                      \
        --repository "aerospike-client-go" --branch "master"                    \
        --repository "asmt" --branch "master"                                   \
        --repository "aerospike-server.docker" --branch "master"                \
        --repository "aerospike-server" --branch "master"                       \
        --repository "aerospike-kubernetes-operator" --branch "master"          \
        --repository "aerospike-client-rest" --branch "master"                  \
        --repository "aerospike-tools.docker" --branch "master"                 \
        --repository "aerospike-management-lib" --branch "master"               \
        --repository "aerospike-common" --branch "master"                       \
        --repository "aerospike-mod-lua" --branch "master"                      \
        --repository "aerospike-client-c-dependencies" --branch "master"        \
        --repository "aerospike-monitoring" --branch "master"                   \
        --repository "aerospike-benchmark" --branch "master"                    \
        --repository "aerospike-act" --branch "master"                          \
        --repository "aerospike-tools-validation" --branch "master"

    ProcessPost
}

Process $@
