#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/warmcat"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/warmcat"    \
        --repository "libwebsockets" --branch "main"                            \
        --repository "sai" --branch "main"                                      \
        --repository "gitohashi" --branch "master"                              \
        --repository "lws-esp32-factory" --branch "master"                      \
        --repository "lws-esp32-test-server-demos" --branch "master"

    ProcessPost
}

Process $@
