#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories \
        --remote_base_path "https://github.com/thesofproject"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/thesofproject"  \
        --repository "sof" --branch "main"                                          \
        --repository "sof-test" --branch "main"                                     \
        --repository "sof-bin" --branch "main"                                      \
        --repository "sof-docs" --branch "main"                                     \
        --repository "thesofproject.github.io" --branch "main"                      \
        --repository "rimage" --branch "main"                                       \
        --repository "build-scripts" --branch "main"                                \
        --repository "sof-manifests" --branch "main"

    ProcessPost
}

Process $@
