#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/jermp"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/jermp"  \
        --repository "data_compression_course" --branch "master"            \
        --repository "sshash" --branch "master"                             \
        --repository "pthash" --branch "master"                             \
        --repository "autocomplete" --branch "master"                       \
        --repository "s_indexes" --branch "master"                          \
        --repository "opt_vbyte" --branch "master"                          \
        --repository "mutable_rank_select" --branch "master"                \
        --repository "rdf_indexes" --branch "master"                        \
        --repository "mm_file" --branch "master"                            \
        --repository "essentials" --branch "master"                         \
        --repository "cmd_line_parser" --branch "master"                    \
        --repository "psds" --branch "master"                               \
        --repository "interpolative_coding" --branch "master"               \
        --repository "entropy_coding" --branch "master"                     \
        --repository "dint" --branch "master"                               \
        --repository "clustered_elias_fano_indexes" --branch "master"

    ProcessPost
}

Process $@
