#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/libvips"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/libvips"    \
        --repository "libvips" --branch "master"                                \
        --repository "nip2" --branch "master"                                   \
        --repository "vips-bench" --branch "master"                             \
        --repository "vipsdisp-tiny" --branch "master"

    ProcessPost
}

Process $@
