#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/spring"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/spring" \
        --repository "spring" --branch "develop"                            \
        --repository "spring-website" --branch "master"                     \
        --repository "upq" --branch "master"                                \
        --repository "uberserver" --branch "master"                         \
        --repository "Python" --branch "master"                             \
        --repository "pyunitsync" --branch "master"                         \
        --repository "dev-game.sdd" --branch "master"                       \
        --repository "AAI" --branch "master"                                \
        --repository "spring-website-wiki" --branch "master"                \
        --repository "LobbyProtocol" --branch "master"                      \
        --repository "RAI" --branch "master"                                \
        --repository "spring-ai-includes" --branch "master"                 \
        --repository "menu-game.sdd" --branch "master"                      \
        --repository "menu-map.sdd" --branch "master"                       \
        --repository "testgame" --branch "master"                           \
        --repository "MelBot" --branch "master"

    ProcessPost
}

Process $@
