#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/openMSX"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/openMSX"    \
        --repository "debugger" --branch "master"                               \
        --repository "openMSX" --branch "master"                                \
        --repository "msxtar" --branch "master"

    ProcessPost
}

Process $@
