#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories \
        --remote_base_path "https://github.com/OpenLoco" \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/OpenLoco" \
        --repository "OpenLoco" --branch "bleed" \
        --repository "openloco.github.io" --branch "master" \
        --repository "decompilation-tools" --branch "master" \
        --repository "openloco-docker-build" --branch "master"

    ProcessPost
}

Process $@
