#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/spring"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/spring" \
        --repository "spring" --branch "develop"                            \
        --repository "HughAI" --branch "master"                             \
        --repository "Python" --branch "master"                             \
        --repository "Shard" --branch "master"                              \
        --repository "KAIK" --branch "master"                               \
        --repository "CircuitAI" --branch "master"                          \
        --repository "pyunitsync" --branch "master"                         \
        --repository "pr-downloader" --branch "master"                      \
        --repository "SpringMapConvNG" --branch "master"                    \
        --repository "AAI" --branch "master"

    ProcessPost
}

Process $@
