#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/OpenMW"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/OpenMW" \
        --repository "openmw" --branch "master"                             \
        --repository "collada-exporter" --branch "master"                   \
        --repository "example-suite" --branch "master"                      \
        --repository "openmw.github.io" --branch "master"

    ProcessPost
}

Process $@
