#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://github.com/dolphin-emu"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/dolphin-emu"    \
        --repository "dolphin" --branch "master"                                    \
        --repository "www" --branch "stable"                                        \
        --repository "fifoci" --branch "master"                                     \
        --repository "hwtests" --branch "master"                                    \
        --repository "sadm" --branch "master"                                       \
        --repository "netplay-index" --branch "master"                              \
        --repository "fifoplayer" --branch "master"

    ProcessPost
}

Process $@
