#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/audacity"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/audacity"   \
        --repository "audacity" --branch "master"                               \
        --repository "audacity-support" --branch "master"                       \
        --repository "audacity-actions" --branch "master"                       \
        --repository "audacity-project-tools" --branch "master"                 \
        --repository "audacity-manual" --branch "master"

    ProcessPost
}

Process $@
