#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories \
        --remote_base_path "https://github.com/NightDive-Studio" \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/NightDive-Studio" \
        --repository "shockmac" --branch "master" \
        --repository "strife-ve" --branch "master" \
        --repository "machines" --branch "master" \
        --repository "sin-ex-game" --branch "master"

    ProcessPost
}

Process $@
