#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/cmangos"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/cmangos"    \
        --repository "mangos-tbc" --branch "master"                             \
        --repository "classic-db" --branch "master"                             \
        --repository "mangos-wotlk" --branch "master"                           \
        --repository "mangos-classic" --branch "master"                         \
        --repository "tbc-db" --branch "master"                                 \
        --repository "wotlk-db" --branch "master"                               \
        --repository "mangos-cata" --branch "master"

    ProcessPost
}

Process $@
