#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/OpenRA"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/OpenRA" \
        --repository "OpenRA" --branch "bleed"

    ProcessPost
}

Process $@
