#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessGitRepositories \
        --remote-base-path "https://github.com/runuo" \
        --local-base-path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/runuo" \
        --repository "runuo" --branch "master"

    ProcessCommonPost
}

Process $@
