#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/gbdev"                       \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/gbdev"  \
        --repository "hardware.inc" --branch "master"                       \
        --repository "pandocs" --branch "master"                            \
        --repository "rgbds" --branch "master"                              \
        --repository "gbdev.github.io" --branch "master"                    \
        --repository "database" --branch "master"                           \
        --repository "rgbds-www2" --branch "master"                         \
        --repository "awesome-gbdev" --branch "master"                      \
        --repository "rgbds-www" --branch "master"                          \
        --repository "gb-opcodes" --branch "master"                         \
        --repository "rgbds-obj" --branch "master"                          \
        --repository "rgbobj" --branch "master"

    ProcessPost
}

Process $@
