#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://github.com/chocolate-doom"                      \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/chocolate-doom" \
        --repository "chocolate-doom" --branch "master"                             \
        --repository "master-server" --branch "master"                              \
        --repository "music-packs" --branch "master"                                \
        --repository "statcheck" --branch "master"                                  \
        --repository "icon" --branch "master"

    ProcessPost
}

Process $@
