#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/cc65"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/cc65"   \
        --repository "cc65" --branch "master"                               \
        --repository "ip65" --branch "master"                               \
        --repository "cc65.github.io" --branch "master"                     \
        --repository "doc" --branch "master"                                \
        --repository "wiki" --branch "master"

    ProcessPost
}

Process $@
