#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/OpenTTD"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/OpenTTD"    \
        --repository "OpenTTD" --branch "master"                                \
        --repository "wiki-data" --branch "master"                              \
        --repository "appstore-data" --branch "master"                          \
        --repository "nml" --branch "master"                                    \
        --repository "master-server-web" --branch "master"                      \
        --repository "master-server" --branch "master"                          \
        --repository "game-coordinator" --branch "master"                       \
        --repository "bananas-server" --branch "master"                         \
        --repository "BaNaNaS" --branch "master"                                \
        --repository "bananas-frontend-web" --branch "master"                   \
        --repository "bananas-frontend-cli" --branch "master"                   \
        --repository "bananas-api" --branch "master"                            \
        --repository "OpenMSX" --branch "master"                                \
        --repository "OpenSFX" --branch "master"                                \
        --repository "OpenGFX" --branch "master"                                \
        --repository "actions" --branch "master"                                \
        --repository "website" --branch "master"                                \
        --repository "py-protocol" --branch "master"                            \
        --repository "workflows" --branch "master"                              \
        --repository "aws-infra" --branch "master"

    ProcessPost
}

Process $@
