#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessGitRepositories \
        --remote-base-path "https://github.com/electronicarts" \
        --local-base-path "${SERVER_PC_DEVELOPMENT_PATH}/github.com/electronicarts" \
        --repository "CnC_Remastered_Collection" --branch "master" \
        --repository "EASTL" --branch "master" \
        --repository "EABase" --branch "master" \
        --repository "EACopy" --branch "master" \
        --repository "EAStdC" --branch "master" \
        --repository "EAThread" --branch "master" \
        --repository "EATest" --branch "master" \
        --repository "EAMain" --branch "master" \
        --repository "EAAssert" --branch "master"

    ProcessCommonPost
}

Process $@
