#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    SynchronizeGitRepositories                                                                                          \
        --remote_upstream_base_path "ssh://wpieterse2825@gmail.com@source.developers.google.com:2022/p/wpieterse-me/r"  \
        --remote_origin_base_path "git@gitlab.com:wpieterse-me"                                                         \
        --local_base_path "${SERVER_MIDGARD_PATH}/gitlab.com/wpieterse-me"                                              \
        --repository "personal" --branch "master"                                                                       \
        --repository "synchronizer" --branch "master"

    ProcessPost
}

Process $@
