#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://github.com/electronicarts"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/electronicarts"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/electronicarts"

REPOSITORY_CNC_REMASTERED_COLLECTION_NAME="CnC_Remastered_Collection"
REPOSITORY_EASTL_NAME="EASTL"
REPOSITORY_EABASE_NAME="EABase"
REPOSITORY_EACOPY_NAME="EACopy"
REPOSITORY_EASTDC_NAME="EAStdC"
REPOSITORY_EATHREAD_NAME="EAThread"
REPOSITORY_EATEST_NAME="EATest"
REPOSITORY_EAMAIN_NAME="EAMain"
REPOSITORY_EAASSERT_NAME="EAAssert"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_CNC_REMASTERED_COLLECTION_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_CNC_REMASTERED_COLLECTION_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EASTL_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EASTL_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EABASE_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EABASE_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EACOPY_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EACOPY_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EASTDC_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EASTDC_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EATHREAD_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EATHREAD_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EATEST_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EATEST_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EAMAIN_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EAMAIN_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_EAASSERT_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_EAASSERT_NAME}" \
        --branch "master"

    ProcessCommonPost
}

Process $@
