#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                        \
        --remote_base_path "https://github.com/GPUOpen-Drivers"                 \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/GPUOpen-Drivers"   \
        --repository "xgl" --branch "dev"                                       \
        --repository "pal" --branch "dev"

    ProcessPost
}

Process $@
