#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                            \
        --remote_base_path "https://github.com/RPCS3"               \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/RPCS3" \
        --repository "rpcs3" --branch "master"

    ProcessPost
}

Process $@
