#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/raspberrypi"                 \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/raspberrypi"   \
        --repository "pico-sdk" --branch "master"                           \
        --repository "pico-extras" --branch "master"

    ProcessPost
}

Process $@
