#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                \
        --remote_base_path "https://github.com/brongo"                  \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/brongo"    \
        --repository "eternal-010-templates" --branch "main"            \
        --repository "SAMUEL" --branch "main"

    ProcessPost
}

Process $@
