#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "https://github.com/id-Software"                 \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/id-Software"   \
        --repository "DOOM" --branch "master"                               \
        --repository "DOOM-3" --branch "master"                             \
        --repository "DOOM-3-BFG" --branch "master"                         \
        --repository "DOOM-iOS" --branch "master"                           \
        --repository "DOOM-IOS2" --branch "master"                          \
        --repository "Enemy-Territory" --branch "master"                    \
        --repository "GtkRadiant" --branch "master"                         \
        --repository "idsetup" --branch "master"                            \
        --repository "Quake" --branch "master"                              \
        --repository "Quake-2" --branch "master"                            \
        --repository "Quake-2-Tools" --branch "master"                      \
        --repository "Quake-III-Arena" --branch "master"                    \
        --repository "Quake-Tools" --branch "master"                        \
        --repository "RTCW-MP" --branch "master"                            \
        --repository "RTCW-SP" --branch "master"                            \
        --repository "wolf3d" --branch "master"                             \
        --repository "wolf3d-browser" --branch "master"                     \
        --repository "Wolf3D-iOS" --branch "master"

    ProcessPost
}

Process $@
