#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                            \
        --remote_base_path "https://github.com/CornN64"               \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/CornN64" \
        --repository "esp_8_bit" --branch "master"

    ProcessPost
}

Process $@
