#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CallSubScripts                          \
        --root "${THIS_SCRIPT_DIRECTORY}"   \
        --script "clone_chocolate-doom"     \
        --script "clone_coelckers"          \
        --script "clone_dhewm"              \
        --script "clone_espressif"          \
        --script "clone_id-Software"        \
        --script "clone_ioquake"            \
        --script "clone_Novum"              \
        --script "clone_raspberrypi"        \
        --script "clone_RobertBeckebans"    \
        --script "clone_suijingfeng"        \
        --script "clone_wpieterse-me"       \
        --script "clone_yquake2"

    ProcessPost
}

Process $@
