#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                \
        --remote_base_path "https://github.com/iortcw"                  \
        --local_base_path "${SERVER_MIDGARD_PATH}/github.com/iortcw"    \
        --repository "iortcw" --branch "master"

    ProcessPost
}

Process $@
