#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://github.com/GPUOpen-Drivers"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/GPUOpen-Drivers"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/GPUOpen-Drivers"

REPOSITORY_PAL_NAME="pal"
REPOSITORY_SPVGEN_NAME="spvgen"
REPOSITORY_AMDVLK_NAME="AMDVLK"
REPOSITORY_XGL_NAME="xgl"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_PAL_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_PAL_NAME}" \
        --branch "dev"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_SPVGEN_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_SPVGEN_NAME}" \
        --branch "dev"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_AMDVLK_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_AMDVLK_NAME}" \
        --branch "dev"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_XGL_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_XGL_NAME}" \
        --branch "dev"

    ProcessCommonPost
}

Process $@
