#!/bin/bash

source "/shared/randoms/synchronizer/shared"

SCRIPT_PATH="${SYNCHRONIZER_REPOSITORY_PATH}/targets/development/repositories/github.com"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-clone)
                declare DISABLE_CLONE=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    local REPOSITORIES_ARGUMENTS=()

    REPOSITORIES_ARGUMENTS+=("--disable-clear")

    if [ ! -z "${DISABLE_CLONE}" ];
    then
        REPOSITORIES_ARGUMENTS+=("--disable-clone")
    fi

    if [ ! -z "${DISABLE_BUILD}" ];
    then
        REPOSITORIES_ARGUMENTS+=("--disable-build")
    fi

    "${SCRIPT_PATH}/axboe/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/chocolate-doom/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/dhewm3/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/id-Software/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/intel/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/KhronosGroup/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/prinexyz/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/RobertBeckebans/process" ${REPOSITORIES_ARGUMENTS[@]}
    "${SCRIPT_PATH}/wpietersexyz/process" ${REPOSITORIES_ARGUMENTS[@]}
}

Process $@
