#!/bin/bash

source "/shared/randoms/synchronizer/variables"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/randoms"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-prune)
                declare DISABLE_PRUNE=1
                ;;
            *)
                LogError "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    if [ -z "${DISABLE_PRUNE}" ];
    then
        echo "=== PRUNNING UNUSED CONTAINERS ========================================================================================="
        echo ""

        docker image prune --force

        echo ""
    fi
}

Process $@
