#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://gitee.com/openarkcompiler"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/gitee.com/openarkcompiler"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/gitee.com/openarkcompiler"

REPOSITORY_OPENARKCOMPILER_NAME="OpenArkCompiler"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_OPENARKCOMPILER_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_OPENARKCOMPILER_NAME}" \
        --branch "master"

    ProcessCommonPost
}

Process $@
