#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://gitlab.com/qemu-project"                        \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/gitlab.com/qemu-project"   \
        --repository "qemu" --branch "master"

    ProcessPost
}

Process $@
