#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories \
        --remote_base_path "git://git.ffmpeg.org" \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/git.ffmpeg.org" \
        --repository "ffmpeg" --branch "master"

    ProcessPost
}

Process $@
