#!/bin/bash

source "/shared/randoms/synchronizer/shared"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/development"

SHARED_TOOLCHAIN_PATH="${LOCAL_ROOT_PATH}/toolchain/Dockerfile"
SHARED_TOOLCHAIN_TAG="development-toolchain"
SHARED_TOOLCHAIN_ROOT="${LOCAL_ROOT_PATH}/toolchain"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-prune)
                declare DISABLE_PRUNE=1
                ;;
            --disable-toolchain)
                declare DISABLE_TOOLCHAIN=1
                ;;
            --disable-repositories)
                declare DISABLE_REPOSITORIES=1
                ;;
            --disable-repositories-clone)
                declare DISABLE_REPOSITORIES_CLONE=1
                ;;
            --disable-repositories-build)
                declare DISABLE_REPOSITORIES_BUILD=1
                ;;
            *)
                LogError "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    if [ -z "${DISABLE_TOOLCHAIN}" ];
    then
        echo "************************************************************************************************************************"
        echo "* DEVELOPMENT TOOLCHAIN                                                                                                *"
        echo "************************************************************************************************************************"
        echo ""

        echo "=== BUILD CONTAINER IMAGE =============================================================================================="
        echo ""

        docker \
            build \
                --file ${SHARED_TOOLCHAIN_PATH} \
                --tag ${SHARED_TOOLCHAIN_TAG} \
                ${SHARED_TOOLCHAIN_ROOT}

        echo ""
    fi

    if [ -z "${DISABLE_REPOSITORIES}" ];
    then
        local REPOSITORIES_ARGUMENTS=()

        REPOSITORIES_ARGUMENTS+=("--disable-clear")
        REPOSITORIES_ARGUMENTS+=("--disable-prune")

        if [ ! -z "${DISABLE_REPOSITORIES_CLONE}" ];
        then
            REPOSITORIES_ARGUMENTS+=("--disable-clone")
        fi

        if [ ! -z "${DISABLE_REPOSITORIES_BUILD}" ];
        then
            REPOSITORIES_ARGUMENTS+=("--disable-build")
        fi

        "${LOCAL_ROOT_PATH}/repositories/process" ${REPOSITORIES_ARGUMENTS[@]}
    fi

    if [ -z "${DISABLE_PRUNE}" ];
    then
        echo "=== PRUNNING UNUSED CONTAINERS ========================================================================================="
        echo ""

        docker image prune --force

        echo ""
    fi
}

Process $@
