#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

PROCESS_AXBOE_SCRIPT="${THIS_SCRIPT_DIRECTORY}/axboe/process"
PROCESS_CHOCOLATE_DOOM_SCRIPT="${THIS_SCRIPT_DIRECTORY}/chocolate-doom/process"
PROCESS_DHEWM3_SCRIPT="${THIS_SCRIPT_DIRECTORY}/dhewm3/process"
PROCESS_ID_SOFTWARE_SCRIPT="${THIS_SCRIPT_DIRECTORY}/id-Software/process"
PROCESS_INTEL_SCRIPT="${THIS_SCRIPT_DIRECTORY}/intel/process"
PROCESS_KHRONOSGROUP_SCRIPT="${THIS_SCRIPT_DIRECTORY}/KhronosGroup/process"
PROCESS_LLVM_SCRIPT="${THIS_SCRIPT_DIRECTORY}/llvm/process"
PROCESS_POCL_SCRIPT="${THIS_SCRIPT_DIRECTORY}/pocl/process"
PROCESS_PRINEXYZ_SCRIPT="${THIS_SCRIPT_DIRECTORY}/prinexyz/process"
PROCESS_ROBERTBECKEBANS_SCRIPT="${THIS_SCRIPT_DIRECTORY}/RobertBeckebans/process"
PROCESS_WPIETERSEXYZ_SCRIPT="${THIS_SCRIPT_DIRECTORY}/wpietersexyz/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    if [[ ${PARAMETER_DISABLE_REPOSITORIES} -eq 0 ]];
    then
        ProcessCallSubScripts \
            "${PROCESS_AXBOE_SCRIPT}" \
            "${PROCESS_CHOCOLATE_DOOM_SCRIPT}" \
            "${PROCESS_DHEWM3_SCRIPT}" \
            "${PROCESS_ID_SOFTWARE_SCRIPT}" \
            "${PROCESS_INTEL_SCRIPT}" \
            "${PROCESS_KHRONOSGROUP_SCRIPT}" \
            "${PROCESS_LLVM_SCRIPT}" \
            "${PROCESS_POCL_SCRIPT}" \
            "${PROCESS_PRINEXYZ_SCRIPT}" \
            "${PROCESS_ROBERTBECKEBANS_SCRIPT}" \
            "${PROCESS_WPIETERSEXYZ_SCRIPT}"
    fi

    ProcessCommonPost
}

Process $@
