#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

PROCESS_AXBOE_SCRIPT="${THIS_SCRIPT_DIRECTORY}/axboe/process"
PROCESS_CHOCOLATE_DOOM_SCRIPT="${THIS_SCRIPT_DIRECTORY}/chocolate-doom/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessRepositories \
        "${PROCESS_AXBOE_SCRIPT}" \
        "${PROCESS_CHOCOLATE_DOOM_SCRIPT}"

    ProcessCommonPost
}

Process $@
