#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://github.com/ioquake"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/ioquake"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/ioquake"

REPOSITORY_IOQ3_NAME="ioq3"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_IOQ3_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_IOQ3_NAME}" \
        --branch "main"

    ProcessCMake \
        --source-path "${REPOSITORY_LOCAL_BASE_PATH}/${REPOSITORY_IOQ3_NAME}/code" \
        --build-path "${BUILD_BASE_PATH}/${REPOSITORY_IOQ3_NAME}" \
        --extra-parameters "-Wno-dev"

    ProcessCommonPost
}

Process $@
