#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://github.com/FrictionalGames"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/FrictionalGames"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/FrictionalGames"

REPOSITORY_AMNESIA_A_MACHINE_FOR_PIGS_NAME="AmnesiaAMachineForPigs"
REPOSITORY_AMNESIA_THE_DARK_DESCENT_NAME="AmnesiaTheDarkDescent"
REPOSITORY_HPL1_ENGINE_NAME="HPL1Engine"
REPOSITORY_PENUMBRA_OVERTURE_NAME="PenumbraOverture"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_AMNESIA_A_MACHINE_FOR_PIGS_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_AMNESIA_A_MACHINE_FOR_PIGS_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_AMNESIA_THE_DARK_DESCENT_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_AMNESIA_THE_DARK_DESCENT_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_HPL1_ENGINE_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_HPL1_ENGINE_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_PENUMBRA_OVERTURE_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_PENUMBRA_OVERTURE_NAME}" \
        --branch "master"

    ProcessCommonPost
}

Process $@
