#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

PROCESS_WPIETERSE2825_SCRIPT="${THIS_SCRIPT_DIRECTORY}/wpieterse2825/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    if [[ ${PARAMETER_DISABLE_REPOSITORIES} -eq 0 ]];
    then
        ProcessCallSubScripts \
            "${PROCESS_WPIETERSE2825_SCRIPT}"
    fi

    ProcessCommonPost
}

Process $@
