#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://github.com/google"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/google"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/google"

REPOSITORY_SWIFTSHADER_NAME="swiftshader"
REPOSITORY_ZETASQL_NAME="zetasql"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    #
    # FIXME: A sub-module requires a password.
    #
    # PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_SWIFTSHADER_NAME}"
    #
    # ProcessGitRepository \
    #     --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
    #     --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
    #     --name "${REPOSITORY_SWIFTSHADER_NAME}" \
    #     --branch "master"
    #

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_ZETASQL_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_ZETASQL_NAME}" \
        --branch "master"

    ProcessCommonPost
}

Process $@
