#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="https://github.com/microsoft"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/microsoft"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/microsoft"

REPOSITORY_DIRECTXSHADERCOMPILER_NAME="DirectXShaderCompiler"
REPOSITORY_DIRECTX_SPECS_NAME="DirectX-Specs"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_DIRECTXSHADERCOMPILER_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_DIRECTXSHADERCOMPILER_NAME}" \
        --branch "master"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_DIRECTX_SPECS_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_DIRECTX_SPECS_NAME}" \
        --branch "master"

    ProcessCommonPost
}

Process $@
