#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                                                        \
        --remote_base_path "ssh://wpieterse2825@gmail.com@source.developers.google.com:2022/p/wpieterse-me/r"   \
        --local_base_path "${SERVER_MIDGARD_PATH}/source.cloud.google.com/wpieterse-me"                         \
        --repository "personal" --branch "master"

    ProcessPost
}

Process $@
