#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

BASE_SCRIPT="${THIS_SCRIPT_DIRECTORY}/base/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessCallSubScripts \
        "${BASE_SCRIPT}"

    ProcessCommonPost
}

Process $@
