#!/bin/bash

source "/shared/randoms/synchronizer/shared"

SCRIPT_PATH="${SYNCHRONIZER_REPOSITORY_PATH}/targets/development/repositories/github.com/intel"

REPOSITORY_REMOTE_BASE_PATH="github.com/intel"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_SHARED_DEVELOPMENT_PATH}/github.com/intel"
BUILD_BASE_PATH="${SERVER_SHARED_BUILDS_OTHER_PATH}/github.com/intel"

declare -a METRICS_DISCOVERY_CMAKE_BUILD_TYPES=(
    "debug"
    "release"
)

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-clone)
                declare DISABLE_CLONE=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/intel/metrics-discovery                                                                                   *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
            --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}"   \
            --name "metrics-discovery"                      \
            --branch "master"
    fi

    if [ -z "${DISABLE_BUILD}" ];
    then
        for CURRENT_COMPILER in "${SUPPORTED_COMPILERS[@]}"
        do
            for CURRENT_BUILD_TYPE in "${METRICS_DISCOVERY_CMAKE_BUILD_TYPES[@]}"
            do
                ProcessCMakeGenerate                                            \
                    --source-path "${REPOSITORY_LOCAL_BASE_PATH}/metrics-discovery" \
                    --build-path "${BUILD_BASE_PATH}/metrics-discovery"        \
                    --extra-parameters "-Wno-dev"                               \
                    --compiler ${CURRENT_COMPILER}                              \
                    --build-type ${CURRENT_BUILD_TYPE}

                ProcessCMakeBuild                                               \
                    --source-path "${REPOSITORY_LOCAL_BASE_PATH}/metrics-discovery" \
                    --build-path "${BUILD_BASE_PATH}/metrics-discovery"        \
                    --compiler ${CURRENT_COMPILER}                              \
                    --build-type ${CURRENT_BUILD_TYPE}

                ProcessCMakeInstall                                             \
                    --source-path "${REPOSITORY_LOCAL_BASE_PATH}/metrics-discovery" \
                    --build-path "${BUILD_BASE_PATH}/metrics-discovery"        \
                    --compiler ${CURRENT_COMPILER}                              \
                    --build-type ${CURRENT_BUILD_TYPE}
            done
        done
    fi

    echo ""
}

Process $@
