#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

COMPOSE_SCRIPT="${THIS_SCRIPT_DIRECTORY}/compose.yaml"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    if [[ ${PARAMETER_DISABLE_DELUGE} -eq 0 ]];
    then
        PrintBanner "Deluge Compose"

        docker-compose \
            --project-name "deluge-project" \
            --file "${COMPOSE_SCRIPT}" \
            up \
                --detach \
                --force-recreate \
                --build \
                --remove-orphans
    fi

    ProcessCommonPost
}

Process $@
