#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

PROCESS_GIT_KERNEL_ORG_SCRIPT="${THIS_SCRIPT_DIRECTORY}/git.kernel.org/process"
PROCESS_GITHUB_COM_SCRIPT="${THIS_SCRIPT_DIRECTORY}/github.com/process"
PROCESS_GITLAB_COM_SCRIPT="${THIS_SCRIPT_DIRECTORY}/gitlab.com/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    if [[ ${PARAMETER_DISABLE_REPOSITORIES} -eq 0 ]];
    then
        ProcessCallSubScripts \
            "${PROCESS_GIT_KERNEL_ORG_SCRIPT}" \
            "${PROCESS_GITHUB_COM_SCRIPT}" \
            "${PROCESS_GITLAB_COM_SCRIPT}"
    fi

    ProcessCommonPost
}

Process $@
