---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Africa/Johannesburg"
      - VERSION=docker
    volumes:
      - /shared/content/.private/plex/config:/config
      - /shared/content/.private/plex/transcode:/transcode
      - /shared/content/movies:/data/movies
      - /shared/content/music:/data/music
      - /shared/content/pictures:/data/pictures
      - /shared/content/series:/data/series
