#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    PrintBanner "server_midgard_git-synchronize"

    docker build                                                                \
        --tag server_midgard_git-synchronize                             \
        --file "${THIS_SCRIPT_DIRECTORY}/process_git_synchronize.Dockerfile"    \
        ${THIS_SCRIPT_DIRECTORY}

    echo ""

    ProcessPost
}

Process $@
