#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    PrintBanner "server_midgard_git-common"

    docker build                                                        \
        --tag server_midgard_git-common                          \
        --build-arg USER_ID=$(id -u)                                    \
        --build-arg GROUP_ID=$(id -g)                                   \
        --file "${THIS_SCRIPT_DIRECTORY}/process_git_common.Dockerfile" \
        ${THIS_SCRIPT_DIRECTORY}

    echo ""

    ProcessPost
}

Process $@
