#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Containers {
    CallSubScripts                                  \
        --root "${THIS_SCRIPT_DIRECTORY}"           \
        --script "process_git_common"               \
        --script "process_git_clone"                \
        --script "process_git_synchronize"
}

function Clone {
    CallSubScripts                                              \
        --root "${THIS_SCRIPT_DIRECTORY}"                       \
        --script "source.cloud.google.com/clone_wpieterse-me"   \
        --script "github.com/clone_wpieterse-me"                \
        --script "gitlab.com/clone_wpieterse-me"                \
        --script "github.com/clone_chocolate-doom"              \
        --script "github.com/clone_coelckers"                   \
        --script "github.com/clone_dhewm"                       \
        --script "github.com/clone_espressif"                   \
        --script "github.com/clone_id-Software"                 \
        --script "github.com/clone_ioquake"                     \
        --script "github.com/clone_Novum"                       \
        --script "github.com/clone_raspberrypi"                 \
        --script "github.com/clone_RobertBeckebans"             \
        --script "github.com/clone_suijingfeng"                 \
        --script "github.com/clone_yquake2"
}

function Process {
    ProcessPre $@

    Containers
    Clone

    ProcessPost
}

Process $@
