#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Clone {
    CallSubScripts                                  \
        --root "${THIS_SCRIPT_DIRECTORY}"           \
        --script "github.com/clone"
}

function Build {
    CallSubScripts                                  \
        --root "${THIS_SCRIPT_DIRECTORY}"           \
        --script "github.com/build"
}

function Process {
    ProcessPre $@

    Clone
    Build

    ProcessPost
}

Process $@
