#!/bin/bash

source "/shared/randoms/synchronizer/shared"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/development/repositories/github.com/id-Software"

REMOTE_DEVELOPMENT_PATH="github.com/id-Software"
LOCAL_DEVELOPMENT_PATH="${DEVELOPMENT_ROOT_PATH}/github.com/id-Software"
LOCAL_BUILD_PATH="${BUILDS_OTHER_ROOT_PATH}/server-pc/github.com/id-Software"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-clone)
                declare DISABLE_CLONE=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/DOOM                                                                                          *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "DOOM"                                   \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/DOOM-3                                                                                        *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "DOOM-3"                                 \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/DOOM-3-BFG                                                                                    *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "DOOM-3-BFG"                             \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/DOOM-iOS                                                                                      *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "DOOM-iOS"                               \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/DOOM-IOS2                                                                                     *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "DOOM-IOS2"                              \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Enemy-Territory                                                                               *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Enemy-Territory"                        \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/GtkRadiant                                                                                    *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "GtkRadiant"                             \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/idsetup                                                                                       *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "idsetup"                                \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Quake                                                                                         *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Quake"                                  \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Quake-2                                                                                       *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Quake-2"                                \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Quake-2-Tools                                                                                 *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Quake-2-Tools"                          \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Quake-III-Arena                                                                               *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Quake-III-Arena"                        \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Quake-Tools                                                                                   *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Quake-Tools"                            \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/RTCW-MP                                                                                       *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "RTCW-MP"                                \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/RTCW-SP                                                                                       *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "RTCW-SP"                                \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/wolf3d                                                                                        *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "wolf3d"                                 \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/wolf3d-browser                                                                                *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "wolf3d-browser"                         \
            --branch "master"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/id-Software/Wolf3D-iOS                                                                                    *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "Wolf3D-iOS"                             \
            --branch "master"
    fi

    echo ""
}

Process $@
