#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="github.com/chocolate-doom"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/chocolate-doom"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/chocolate-doom"

REPOSITORY_CHOCOLATE_DOOM_NAME="chocolate-doom"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_CHOCOLATE_DOOM_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_CHOCOLATE_DOOM_NAME}" \
        --branch "master"

    ProcessCMake \
        --source-path "${REPOSITORY_LOCAL_BASE_PATH}/${REPOSITORY_CHOCOLATE_DOOM_NAME}" \
        --build-path "${BUILD_BASE_PATH}/${REPOSITORY_CHOCOLATE_DOOM_NAME}" \
        --extra-parameters "-Wno-dev"

    ProcessCommonPost
}

Process $@
