#!/bin/bash

source "/shared/randoms/synchronizer/shared"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/development/repositories/github.com/wpietersexyz"

REMOTE_DEVELOPMENT_PATH="github.com/wpietersexyz"
LOCAL_DEVELOPMENT_PATH="${DEVELOPMENT_ROOT_PATH}/github.com/wpietersexyz"
LOCAL_BUILD_PATH="${BUILDS_PERSONAL_ROOT_PATH}/server-pc/github.com/wpietersexyz"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-clone)
                declare DISABLE_CLONE=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/game-assets                                                                                  *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "game-assets"                            \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/open-nt-400                                                                                  *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "open-nt-400"                            \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/scrapbook                                                                                    *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "scrapbook"                              \
            --branch "main"
    fi

    if [ -z "${DISABLE_BUILD}" ];
    then
        ProcessCMake                                            \
            --source-path "${LOCAL_DEVELOPMENT_PATH}/scrapbook" \
            --build-path "${LOCAL_BUILD_PATH}/scrapbook"        \
            --extra-parameters "-DUNUSED=OFF"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/unrealengine-1-1996                                                                          *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "unrealengine-1-1996"                    \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/unrealengine-1-1997                                                                          *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "unrealengine-1-1997"                    \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/windows-10                                                                                   *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "windows-10"                             \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/windows-nt-350                                                                               *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "windows-nt-350"                         \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/windows-nt-400                                                                               *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "windows-nt-400"                         \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/windows-nt-600                                                                               *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "windows-nt-600"                         \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/windows-research-kernel                                                                      *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "windows-research-kernel"                \
            --branch "main"
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/xbox                                                                                         *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "xbox"                                   \
            --branch "main"
    fi

    echo ""
}

Process $@
