#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

REPOSITORY_REMOTE_BASE_PATH="github-prinexyz:prinexyz"
REPOSITORY_LOCAL_BASE_PATH="${SERVER_PC_SHARED_DEVELOPMENT_PATH}/github.com/prinexyz"
BUILD_BASE_PATH="${SERVER_PC_SHARED_BUILDS_OTHER_PATH}/github.com/prinexyz"

REPOSITORY_JHWMANUFACTURING_GITHUB_IO_NAME="jhwmanufacturing.github.io"
REPOSITORY_PAXBOXXYZ_GITHUB_IO_NAME="paxboxxyz.github.io"
REPOSITORY_PRINEXYZ_GITHUB_IO_NAME="prinexyz.github.io"
REPOSITORY_WPIETERSEXYZ_GITHUB_IO_NAME="wpietersexyz.github.io"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_JHWMANUFACTURING_GITHUB_IO_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_JHWMANUFACTURING_GITHUB_IO_NAME}" \
        --branch "main"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_PAXBOXXYZ_GITHUB_IO_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_PAXBOXXYZ_GITHUB_IO_NAME}" \
        --branch "main"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_PRINEXYZ_GITHUB_IO_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_PRINEXYZ_GITHUB_IO_NAME}" \
        --branch "main"

    PrintBanner "${REPOSITORY_REMOTE_BASE_PATH}/${REPOSITORY_WPIETERSEXYZ_GITHUB_IO_NAME}"

    ProcessGitRepository \
        --remote-base-path "${REPOSITORY_REMOTE_BASE_PATH}" \
        --local-base-path "${REPOSITORY_LOCAL_BASE_PATH}" \
        --name "${REPOSITORY_WPIETERSEXYZ_GITHUB_IO_NAME}" \
        --branch "main"

    ProcessCommonPost
}

Process $@
