#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessGitRepositories \
        --remote-base-path "git://git.savannah.gnu.org/git" \
        --local-base-path "${SERVER_PC_DEVELOPMENT_PATH}/git.savannah.gnu.org/git" \
        --repository "grub" --branch "master" \
        --repository "grub-extras" --branch "master"

    ProcessCommonPost
}

Process $@
