#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessGitRepositories \
        --remote-base-path "https://git.freebsd.org" \
        --local-base-path "${SERVER_PC_DEVELOPMENT_PATH}/git.freebsd.org" \
        --repository "doc" --branch "main" \
        --repository "ports" --branch "main" \
        --repository "src" --branch "main"

    ProcessCommonPost
}

Process $@
