#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                            \
        --remote_base_path "https://gitlab.gnome.org/GNOME"                         \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/gitlab.gnome.org/GNOME"    \
        --repository "gimp" --branch "master"                                       \
        --repository "glib" --branch "main"                                         \
        --repository "gparted" --branch "master"

    ProcessPost
}

Process $@
