#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    CloneGitRepositories                                                    \
        --remote_base_path "git://git.blender.org"                          \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/git.blender.org"   \
        --repository "blender" --branch "master"

    ProcessPost
}

Process $@
