#!/bin/bash

source "/shared/randoms/synchronizer/shared"

SCRIPT_PATH="${SYNCHRONIZER_REPOSITORY_PATH}/targets/personal/repositories/github.com/wpietersexyz"

REPOSITORY_REMOTE_BASE_PATH="github-wpietersexyz:wpietersexyz"
REPOSITORY_LOCAL_BASE_PATH="${PERSONAL_HOME_REPOSITORIES_PATH}/github.com/wpietersexyz"
BUILD_BASE_PATH="${PERSONAL_HOME_BUILDS_PATH}/github.com/wpietersexyz"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/wpietersexyz/scrapbook                                                                                    *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_BUILD}" ];
    then
        ProcessBazel                                                \
            --source-path "${REPOSITORY_LOCAL_BASE_PATH}/scrapbook" \
            --build-path "${BUILD_BASE_PATH}/scrapbook"
    fi

    echo ""
}

Process $@
