FROM development-cmake:latest

RUN apt \
        install \
            --yes \
            --no-install-recommends \
            --no-install-suggests \
            zlib1g-dev \
            libopenal-dev \
            libsdl2-dev \
            libcurl4-openssl-dev \
            libjpeg-dev \
            libogg-dev \
            libvorbis-dev
