#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    SynchronizeGitRepositories                                                                                              \
        --remote_upstream_base_path "git@github.com:wpieterse2825"                                                          \
        --remote_origin_base_path "ssh://wpieterse2825@gmail.com@source.developers.google.com:2022/p/wpieterse-general/r"   \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/source.cloud.google.com/wpieterse2825"                             \
        --repository "game-assets" --branch "main"                                                                          \
        --repository "open-nt-400" --branch "main"                                                                          \
        --repository "prey-sdk" --branch "main"                                                                             \
        --repository "quake-4-sdk" --branch "main"                                                                          \
        --repository "quake-wars-sdk" --branch "main"                                                                       \
        --repository "synchronizer" --branch "main"                                                                         \
        --repository "unrealengine-1-1996" --branch "main"                                                                  \
        --repository "unrealengine-1-1997" --branch "main"                                                                  \
        --repository "windows-10" --branch "main"                                                                           \
        --repository "windows-nt-350" --branch "main"                                                                       \
        --repository "windows-nt-400" --branch "main"                                                                       \
        --repository "windows-nt-600" --branch "main"                                                                       \
        --repository "windows-research-kernel" --branch "main"                                                              \
        --repository "xbox" --branch "main"

    SynchronizeGitRepositories                                                                                              \
        --remote_upstream_base_path "git@github.com:wpieterse2825"                                                          \
        --remote_origin_base_path "ssh://wpieterse2825@gmail.com@source.developers.google.com:2022/p/wpieterse-paxbox/r"    \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/source.cloud.google.com/wpieterse2825"                             \
        --repository "paxbox" --branch "main"

    ProcessPost
}

Process $@
