#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    SynchronizeGitRepositories                                                                                              \
        --remote_upstream_base_path "git@github.com:wpieterse2825"                                                          \
        --remote_origin_base_path "ssh://wpieterse2825@gmail.com@source.developers.google.com:2022/p/wpieterse-paxbox/r"    \
        --local_base_path "${SERVER_PC_DEVELOPMENT_PATH}/source.cloud.google.com/wpieterse-paxbox"                          \
        --repository "paxbox" --branch "main"

    ProcessPost
}

Process $@
