#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

SERVICES_SCRIPT="${THIS_SCRIPT_DIRECTORY}/services/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    "${SERVICES_SCRIPT}" \
        --disable-clear \
        --disable-prune

    ProcessCommonPost
}

Process $@
