#!/bin/bash

set -e

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

function Process {
    ProcessPre $@

    PrintBanner "plex-project"

    docker-compose                                                  \
        --project-name "plex-project"                               \
        --file "${THIS_SCRIPT_DIRECTORY}/process_service_plex.yaml" \
        up                                                          \
            --detach                                                \
            --force-recreate                                        \
            --build                                                 \
            --remove-orphans

    ProcessPost
}

Process $@
