#!/bin/bash

THIS_SCRIPT_DIRECTORY="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
ROOT_SCRIPT_DIRECTORY="${THIS_SCRIPT_DIRECTORY}/../../../../.."

source "${ROOT_SCRIPT_DIRECTORY}/shared"

PROCESS_WPIETERSEXYZ_SCRIPT="${THIS_SCRIPT_DIRECTORY}/wpietersexyz/process"

function Process {
    ProcessCommonArguments $@
    ProcessCommonPre

    ProcessRepositories \
        "${PROCESS_WPIETERSEXYZ_SCRIPT}"

    ProcessCommonPost
}

Process $@
