#!/bin/bash

source "/shared/randoms/synchronizer/shared"

LOCAL_ROOT_PATH="${SYNCHRONIZER_ROOT_PATH}/targets/development/repositories/github.com/RobertBeckebans"

REMOTE_DEVELOPMENT_PATH="github.com/RobertBeckebans"
LOCAL_DEVELOPMENT_PATH="${DEVELOPMENT_ROOT_PATH}/github.com/RobertBeckebans"
LOCAL_BUILD_PATH="${BUILDS_OTHER_ROOT_PATH}/server-pc/github.com/RobertBeckebans"

function Process {
    while [[ $# -ne 0 ]];
    do
        case $1 in
            --disable-clear)
                declare DISABLE_CLEAR=1
                ;;
            --disable-clone)
                declare DISABLE_CLONE=1
                ;;
            --disable-build)
                declare DISABLE_BUILD=1
                ;;
            *)
                echo "Process: Unknown argument $1."
                exit 1
                ;;
        esac

        shift
    done

    if [ -z "${DISABLE_CLEAR}" ];
    then
        clear
    fi

    echo "************************************************************************************************************************"
    echo "* github.com/RobertBeckebans/RBDOOM-3-BFG                                                                              *"
    echo "************************************************************************************************************************"
    echo ""

    if [ -z "${DISABLE_CLONE}" ];
    then
        ProcessGitRepository                                \
            --remote-base-path "${REMOTE_DEVELOPMENT_PATH}" \
            --local-base-path "${LOCAL_DEVELOPMENT_PATH}"   \
            --name "RBDOOM-3-BFG"                           \
            --branch "master"
    fi

    if [ -z "${DISABLE_BUILD}" ];
    then
        ProcessCMake                                                \
            --source-path "${LOCAL_DEVELOPMENT_PATH}/RBDOOM-3-BFG/neo"  \
            --build-path "${LOCAL_BUILD_PATH}/RBDOOM-3-BFG"         \
            --extra-parameters "-Wno-dev"
    fi

    echo ""
}

Process $@
